title: minima
author: LoganPabel
email: Lo9an1381@yandex.ru
description: > From getting acquainted with github, I want to get a very useful experience and new acquaintances with people from different parts of the globe,I think this journey will be memorable =))
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
